### ISSUE TITLE
[Question] Difference to original package?

### ISSUE THREAD

**Issue by lonix1** [MatthiasKunnen/passport-http-2#1]
How is this different to original package?

That one isn't maintained anymore, so I'm curious about this one.

**Comment by MatthiasKunnen** [comment]
The most important difference has been removing the use of the deprecated buffer constructor (ab1de0ff4739be78fd3ab5e8acecb2be4ef4af09) and changes to adhere to the Basic Authentication specification (da58b3a0825b94be781c22b950635f8d89559032). A major one was that the original implementation failed on passwords with a `:` in them.

**Comment by lonix1** [comment]
Thanks!
